import Hero from "@/components/Hero";
import Head from "next/head";
import Image from "next/image";


export default function Home() {
	return (
		<div>
			<Head>
				<title>Maoutain</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />
		</div>
	);
}
